[package]
name = "yetanotherclown/planck-matter-hooks"
description = "A Plugin for Planck, adding support for the Matter topoRuntime"
license = "MIT"
authors = ["YetAnotherClown"]
version = "0.2.0-rc.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
homepage = "https://yetanotherclown.github.io/planck"
repository = "https://github.com/yetanotherclown/planck"

include = ["wally.lock"]
